---
- hosts: all
  become: true
  tasks:
  
   - name: install apache2 package for CentOs
     apt: 
       name: apache2
       state: latest
       update_cache: yes
     when: ansible_distribution == "CentOS"
