---
- hosts: all
  become: true
  tasks:

  - name: install apache2 package for Red Hat
    dnf: 
      name: apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"
